/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_cs_banjo_application_Banjo_SearchInstance */

#ifndef _Included_edu_duke_cs_banjo_application_Banjo_SearchInstance
#define _Included_edu_duke_cs_banjo_application_Banjo_SearchInstance
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
