/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_cs_banjo_application_Banjo */

#ifndef _Included_edu_duke_cs_banjo_application_Banjo
#define _Included_edu_duke_cs_banjo_application_Banjo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_cs_banjo_application_Banjo
 * Method:    CSModelConstruction
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_banjo_application_Banjo_CSModelConstruction
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
